config/routes.rb
MyApp::Application.routes.draw do
  root :to => "welcome#index"
  resources :member
  resources :country do
    resources :place do
      resources :comment
    end
  end
  post "/member/login" , :to => 'member#login', :as => 'member_login'
  get "/member/logout/user" , :to => 'member#logout', :as =>'member_logout'
  get "/comment/history",:to => 'comment#history' , :as => 'history_view'

end

app/models/albums.rb
require 'carrierwave/orm/activerecord'
class Albums < ActiveRecord::Base
  belongs_to :place
  mount_uploader :avatar, AvatarUploader
  attr_accessible :avatar
  def read_uploader(column)
    self[column]
  end

  def write_uploader(column, identifier)
    self[column] = identifier
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :place
  validates :comment_text , :presence => true, :length => { :minimum => 10}
  attr_accessible :comment_text
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :places
	attr_accessible :country_name, :country_pic , :country_descp
end

app/models/member.rb
class Member < ActiveRecord::Base
	has_many :places
	has_many :comments
	attr_accessible :email, :password
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i , :message =>"is Wrong!!"
	#validates :email, :presence => true , :email_format => {:message => 'is not looking good'}
	validates :password , :presence => true, :length => { :minimum => 8}
	#validates :Re_Password , :presence => true, :length => { :minimum => 8}
	#validates_format_of :Email, :with => 

end

app/models/place.rb
class Place < ActiveRecord::Base
	validates :place_descp , :presence => true , :length => { :minimum => 10 }
	validates :place_location , :presence => true , :length => { :minimum => 10 }
	validates :place_name , :presence => true , :length => { :minimum => 10 }
	validates :place_headtopic , :presence => true , :length => { :minimum => 10 }
	validates :member_id , :presence => true
	belongs_to :country
	belongs_to :member
	has_many :albumss, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	attr_accessible :place_descp, :place_location, :place_name , :place_headtopic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def  index
		@place = Place.find(params[:place_id])
		#binding.pry
	end
	def create
		#render :text => params
		@place = Place.find(params[:place_id])
		@comment = @place.comments.create(params[:comment])
		@comment.member_id = session[:member][:id]
		@comment.save
		redirect_to country_place_comment_index_path(@place.country,@place)
	end
	def history
		@places = Place.where(:member_id => session[:member][:id])
		@comments = Comment.where(:member_id => session[:member][:id])
		#binding.pry
		#render :text => @place
	end
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
	def index
		@countries = Country.all
	end
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
	def create
		repass = params[:Re_Password]
		pass = params[:members][:password]
		@member = Member.new(params[:members])
		if pass == repass
			if @member.save
				session[:member] = @member
				redirect_to root_path
			else
				render 'welcome/index'
			end
		else
			#redirect_to root_path(@member)
			@member.errors.add(:password ," and Re-Password is not equal!")
			render 'welcome/index'
		end
	end
	def login
		@member = Member.where("email = (?) and password = (?)",params[:member][:email],params[:member][:password])
		if @member.present?
			@member = Member.find(@member)
			#binding.pry
			session[:member] = @member
		end
		redirect_to root_path
	end
	def logout
		reset_session
		redirect_to root_path
	end
	
end

app/controllers/place_controller.rb
class PlaceController < ApplicationController
	respond_to :html
	def index
		#render :text => params
		@country = Country.find(params[:country_id])
		#binding.pry
		#@places = @country.places
	end
	def create
		#binding.pry
		#render :text => params.inspect

		@country = Country.find(params[:country_id])
		@place = @country.places.create(params[:place])
		@place.member_id = session[:member][:id]
		if @place.save
			@avatars = params[:avatar]
			#binding.pry
			if @avatars.presence
				@avatars.each do |a|
					#binding.pry
					@album = Albums.new
						@album.place = @place
					@album.avatar = a
					@album.save
					@album.avatar = File.open(@album.avatar.current_path)
					@album.save
					binding.pry		
				end
			end
			redirect_to country_place_index_path(@country)
		else
			@places = @country.places
			render "index"
			#binding.pry
			#redirect_to country_place_index_path(@country)
		end
	end
	def destroy
		@place = Place.destroy(params[:id])
		redirect_to country_place_index_path(@place.country)
	end
	def edit
		@country = Country.find(params[:country_id])
		@place = Place.find(params[:id])
		@albums = @place.albumss
		#binding.pry
		#render :text => @place.inspect
	end
	def update
		@place = Place.find(params[:id])
		@place.update_attributes(params[:place])
		@avatars = params[:avatar]
		if @avatars.presence
			@albums = Albums.where(:place_id => @place.id)
			@albums.destroy_all
			#binding.pry
			@avatars.each do |a|
				#binding.pry
				@album = Albums.new
					@album.place = @place
				@album.avatar = a
				@album.save
				@album.avatar = File.open(@album.avatar.current_path)
				@album.save
				#binding.pry		
			end
		end
		redirect_to country_place_index_path(@place.country)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def  index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/history.html.erb
<%= render 'welcome/header' %>
<div class="container showcountry">
	<div class="row">
		<div class="span12">
			<ul class="nav nav-tabs">
			  <li class="active"><%= link_to 'Post',history_view_path(:anchor =>"Post"),:data => {:toggle => 'tab'}%></li>
			  <li><%= link_to 'Comment',history_view_path(:anchor =>"Comment") ,:data => {:toggle => 'tab'}%></li>
			</ul>

			<!-- Tab panes -->
			<div class="tab-content">
			  <div class="tab-pane active" id="Post">
			  	<% if @places %>
				  	<div class='container'>
				  		<div class='row'>
							<div class="span12">
								<table class="table table-striped">
									<thead>
										<tr>
											<th> # </th>
											<th class='span12'> Place 's Topic</th>
										</tr>
									</thead>
									<tbody>
										<% i = 0 %>
										<% @places.order("id desc").each do |p| %>
											<% if p.place_headtopic.present? %>
												<tr>
													<td><h4><%= i = i + 1 %>. </h4></td>
													<td>
														<h4>
															<%= p.place_headtopic %>
														</h4>Place is : <%= p.place_name %>
														<p class='pull-right'>Post by: <%= p.member.email%> Post Date :  <%= p.created_at.strftime('%d/%m/%Y') %></p>
													</td>
												</tr>
											<% end %>
										<% end %>
									</tbody>
								</table>
							</div>  		
						</div>
				  	</div>
				<% else %>
				<h1> Don't have Your Post</h1>
				<% end %>
			  </div>
			  <div class="tab-pane" id="Comment">
			  	<% if @comments %>
				  	<div class='container'>
				  		<div class='row'>
							<div class="span12">
								<table class="table table-striped">
									<thead>
										<tr>
											<th> # </th>
											<th class='span12'> Place 's Topic</th>
										</tr>
									</thead>
									<tbody>
										<% i = 0 %>
										<% @comments.order("id desc").each do |c| %>
											<% if c.comment_text.present? %>
												<tr>
													<td><h4><%= i = i + 1 %>. </h4></td>
													<td>
														<h4>
															<%= c.comment_text %>
														</h4>Comment At Place : <%= c.place.place_name %>
														<p class='pull-right'>Post by: <%= c.member.email%> Post Date :  <%= c.created_at.strftime('%d/%m/%Y') %></p>
													</td>
												</tr>
											<% end %>
										<% end %>
									</tbody>
								</table>
							</div>  		
						</div>
				  	</div>
				<% else %>
				<h1> Don't have Your Comment</h1>
				<% end %>

			  </div>
			</div>
		</div>
	</div>
</div>

app/views/comment/index.html.erb
<%= render 'welcome/header' %>
<div class="container showcountry">
	<div class="row">
		<div class="span11 headpost">
			<h2> <%= @place.place_headtopic %></h2>
			<h4>Place : <%= @place.place_name %> &nbsp;&nbsp;&nbsp; Location : <%= @place.place_location %></h4>
			<p class="pull-right">Post by <%= @place.member.email %></p>
			<div class="content">
				<%= @place.place_descp %>
			</div>
			<hr/>
			<h3>Images ::</h3>
			<div class="row">
				<div class="span10">
					<% @place.albumss.each do |img| %>
						<%= image_tag img.avatar %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<% if @place.comments.present? %>
		<%= @place.comments.count %> ความคิดเห็น<hr/>
		<% @place.comments.order("id desc").each do |cm|%>
		<div class="row">
			<div class="span11 commentall">
				<%= cm.comment_text %>
				<p class="commentfooter">Comment by : <%= cm.member.email %>  At <%= cm.created_at.strftime('%d/%m/%Y')%></p>
			</div>
		</div>
		<% end %>
	<% end %>
	<br><br><br>
	<% if session[:member] %>
		แสดงความคิดเห็น<hr/>
		<div class="row">
			<div class="span11 newcomment">
				<%= form_for :comment  , :url => country_place_comment_index_path(@place.country,@place) do |c|%>
					<%= c.text_area :comment_text , :rows=>10 ,:placeholder => "Write your Comment"%>
					<%= c.submit "Add Comment" , :class => "btn btn-default" %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/country/index.html.erb
<%= render 'welcome/header' %>
<div class="container showcountry">
	<div class="row">
		<% @countries.each do |c|%>
			<div class="span12">
				<%= image_tag "country/"+c.country_pic %>
				<h2><%= c.country_name %></h2>
				<p>
					<%= c.country_descp %>
				</p>
				<p><%= link_to "View Places »" , country_place_index_path(c) %></p>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/member/_signup.html.erb
    <div class="wrapper pull-right">
      <div class="row">
        <div class="span7">
            <h1>Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <div class="row">
                <div class="span4">
                  <%= form_for :members , :url => member_index_path   do |m|%>
                    <div class="control-group">
                      <%= m.label :email ,"Email",{:class => 'control-label'}%>
                      <div class="controls">
                        <%= m.text_field :email , {:class => 'input-xlarge' , :placeholder => 'Email'}%>
                      </div>
                    </div>
                    <div class="control-group">
                      <%= m.label :password ,"Password" ,{:class => 'control-label'}%>
                      <div class="controls">
                        <%= m.password_field :password , {:class => 'input-xlarge' , :placeholder => 'Password'}%>
                      </div>
                    </div>
                    <div class="control-group">
                      <%= m.label :Re_Password ,{:class => 'control-label'}%>
                      <div class="controls">
                        <%= password_field_tag :Re_Password ,nil, :class => 'input-xlarge' , :placeholder => 'Re - Password'%>
                      </div>
                    </div>
                    <div class="control-group">
                      <div class="controls">
                        <%= m.submit "Sign Up" , {:class => 'btn btn-primary btn-large'}%>
                      </div>
                    </div>
                  <% end %>
                </div>
                <div class="span3">
                  <% if @member %>
                      <div class="alert alert-error">
                        <b>Warning!</b>
                          <% if @member.errors.any? %>
                               <ul>
                                <% @member.errors.full_messages.each do |msg| %>
                                  <li><%= msg %></li>
                                <% end %>
                               </ul>
                          <% end %>
                      </div>
                  <% end %>
                </div>
            </div>
        </div>
      </div>
    </div>

app/views/place/_formedit.html.erb
<%= form_for @country.places , :url => place_edit_path , :html => {:class => "form-horizontal",:multipart => true} do |pp|%>
  <div class="modal-body">
  	
		<div class ="control-group">
			<%= pp.label :place_headtopic,"Topic",{:class => "control-label"}%>
			<div class="controls">
				<%= pp.text_field :place_headtopic  , :placeholder => "Write your Topic"%>
			</div>
		</div>
		<div class ="control-group">
			<%= pp.label :place_name,"Place Name",{:class => "control-label"}%>
			<div class="controls">
				<%= pp.text_field :place_name , :placeholder => "Write your Place Name"%>
			</div>
		</div>
		<div class ="control-group">
			<%= pp.label :place_location,"Place Location",{:class => "control-label"}%>
			<div class="controls">
				<%= pp.text_field :place_location , :placeholder => "Write your Place Location"%>
			</div>
		</div>
		<div class ="control-group">
			<%= pp.label :place_descp,"Place Location",{:class => "control-label"}%>
			<div class="controls">
				<%= pp.text_area :place_descp , :cols=>10 , :rows=>5 , :placeholder => "Write your Place Description"%>
			</div>
		</div>
  	<div class ="control-group">
			<%= label_tag :avatar,"Uploadfile",:class => "control-label" %>
			<div class="controls">
				<%= file_field_tag :avatar ,:multiple => :true , :name =>"avatar[]"%>
			</div>
		</div>
  </div>
  <div class="modal-footer">
  	<%= pp.submit "Save", :class => "btn btn-primary"%>
  </div>
<% end %>				

app/views/place/edit.html.erb
<%= render 'welcome/header'%>
<div class=" showcountry">
	<div class="row">
		<div class="span5 offset2">
			<%= form_for :place ,:url => country_place_path(@country,@place) ,:method => :put, :html => {:class => "form-horizontal",:multipart => true} do |p| %>
				<div class ="control-group">
		  			<%= p.label :place_headtopic,"Topic",{:class => "control-label"}%>
		  			<div class="controls">
		  				<%= p.text_field :place_headtopic  , :placeholder => "Write your Topic"%>
		  			</div>
		  		</div>
		  		<div class ="control-group">
		  			<%= p.label :place_name,"Place Name",{:class => "control-label"}%>
		  			<div class="controls">
		  				<%= p.text_field :place_name , :placeholder => "Write your Place Name"%>
		  			</div>
		  		</div>
		  		<div class ="control-group">
		  			<%= p.label :place_location,"Place Location",{:class => "control-label"}%>
		  			<div class="controls">
		  				<%= p.text_field :place_location , :placeholder => "Write your Place Location"%>
		  			</div>
		  		</div>
		  		<div class ="control-group">
		  			<%= p.label :place_descp,"Place Location",{:class => "control-label"}%>
		  			<div class="controls">
		  				<%= p.text_area :place_descp , :cols=>10 , :rows=>5 , :placeholder => "Write your Place Description"%>
		  			</div>
		  		</div>
			  	<div class ="control-group">
		  			<%= label_tag :avatar,"Uploadfile",:class => "control-label" %>
		  			<div class="controls">
		  				<%= file_field_tag :avatar ,:multiple => :true , :name =>"avatar[]"%>
		  			</div>
		  		</div>
		  		<div class ="control-group">
		  			<div class="controls">
		  				<%= p.submit "Save", :class => "btn btn-primary"%>	  			
		  			</div>
		  		</div>
		 	<% end %>
		</div>
		<div class="span8 offset1">
			<h2>Your Albums</h2>
			<% @albums.each do |img| %>
				<div class="span3">
					<%= image_tag img.avatar , :class => "img-polaroid" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/place/index.html.erb
<%= render 'welcome/header' %>
<div class="container showcountry">
	<div class="row">
		<h1> Welcome To <%= @country.country_name %></h1>
		<div class="wrapper">
		<div class="span12">
			<% if @place %>
				<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<b>Warning!</b>
					<% if @place.errors.any? %>
					   <ul>
					    <% @place.errors.full_messages.each do |msg| %>
					      <li><%= msg %></li>
					    <% end %>
					   </ul>
					<% end %>
				</div>
			<% end %>
		</div>
			<% if session[:member] %>
				<%= link_to country_place_index_path(@country,:anchor => "NewPost") , :class => "btn btn-info" , :role => "button" , :data => {:toggle => "modal"}  do %>
				<i class="icon-plus icon-white"></i>Add Your Post
				<% end %>
			<% end %>
			<% if @country.places.present? %>	
				<div class="container">
					<div class="row showinfo">
						<div class="span12">
							<table class="table table-striped">
								<thead>
									<tr>
										<th> # </th>
										<th class='span12'> Place 's Topic</th>
										<th colspan="2"></th>
									</tr>
								</thead>
								<tbody>
									<% i = 0 %>
									<% @country.places.order("id desc").each do |p| %>
										<% if p.place_headtopic.present? %>
											<tr>
												<td><h4><%= i = i + 1 %>. </h4></td>
												<td><h4><%= link_to p.place_headtopic , country_place_comment_index_path(@country,p) %></h4>Place is : <%= p.place_name %><p class='pull-right'>Post by: <%= p.member.email%> Post Date :  <%= p.created_at.strftime('%d/%m/%Y') %></p></td>
												<% if session[:member] %>
													<% if session[:member][:id] == p.member_id %>
														<td>
															<%= link_to edit_country_place_path(@country,p), :class => "btn btn-info" , :role => "button" , :data => {:toggle => "modal"}  do %>
																<i class="icon-pencil icon-white"></i>Edit
															<% end %>
														</td>
														<td>
															<%= link_to country_place_path(@country,p), :method => :delete, :data => {:confirm => "Are you sure?"} ,:class => "btn btn-info" do %>
																<i class="icon-trash icon-white"></i>Delete
															<% end %>
														</td>
													<% else %>
														<td colspan="2"></td>
													<% end %>
												<% end %>
											</tr>
										<% end %>
									<% end %>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			<% else %>
				<h4>No Post</h4>
			<% end %>
		</div>
	</div>
</div>

<!-- Modal -->

<div id="NewPost" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add New Post </h3>
  </div>
  <%= form_for :place , :url => country_place_index_path(@country) , :html => {:class => "form-horizontal",:multipart => true} do |p|%>
	  <div class="modal-body">
	  	
  		<div class ="control-group">
  			<%= p.label :place_headtopic,"Topic",{:class => "control-label"}%>
  			<div class="controls">
  				<%= p.text_field :place_headtopic  , :placeholder => "Write your Topic"%>
  			</div>
  		</div>
  		<div class ="control-group">
  			<%= p.label :place_name,"Place Name",{:class => "control-label"}%>
  			<div class="controls">
  				<%= p.text_field :place_name , :placeholder => "Write your Place Name"%>
  			</div>
  		</div>
  		<div class ="control-group">
  			<%= p.label :place_location,"Place Location",{:class => "control-label"}%>
  			<div class="controls">
  				<%= p.text_field :place_location , :placeholder => "Write your Place Location"%>
  			</div>
  		</div>
  		<div class ="control-group">
  			<%= p.label :place_descp,"Place Location",{:class => "control-label"}%>
  			<div class="controls">
  				<%= p.text_area :place_descp , :cols=>10 , :rows=>5 , :placeholder => "Write your Place Description"%>
  			</div>
  		</div>
	  	<div class ="control-group">
  			<%= label_tag :avatar,"Uploadfile",:class => "control-label" %>
  			<div class="controls">
  				<%= file_field_tag :avatar ,:multiple => :true , :name =>"avatar[]"%>
  			</div>
  		</div>
	  </div>
	  <div class="modal-footer">
	  	<%= p.submit "Save", :class => "btn btn-primary"%>
	  </div>
  <% end %>
</div>

app/views/welcome/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" id="headermenu">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class='brand'>My_Places</span>
      <div class="nav-collapse collapse">
        <ul class="nav menucontrol">
          <li class="<%= 'active' if params[:controller] == 'welcome' %>"><%= link_to 'Home' , root_path %></li>
          <li class="<%= 'active' if params[:controller] == 'country' || params[:controller] == 'place' || ( params[:controller] == 'comment' && params[:action] != 'history') %>">
            <%= link_to 'Places',country_index_path %>
          </li>
          <% if session[:member] %>
            <li class="<%= 'active' if params[:action] == 'history' && params[:controller] == 'comment' %>"><%= link_to 'My History',history_view_path %></li>
          <% end %>
        </ul>
        <% unless session[:member] %>
          <%= form_for :member , :url => member_login_path , :html => {:class => "navbar-form pull-right"} do |m| %>
            <%= m.text_field :email , :class => "span2" , :placeholder => "Email" %>
            <%= m.password_field :password , :class =>"span2" , :placeholder => "Password" %>
            <%= m.submit "Sign in" , :class => "btn btn-info "%>
          <% end %>
        <% else %>
          <div class="span6 pull-right">
            <%= link_to 'Log out' , member_logout_path,:class=>"btn btn-info pull-right"%>
            <div class="span3 pull-right usershow" >Welcome <%= session[:member][:email] %></div>
            
          </div>
        <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render "welcome/header"%>
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit" style="width:100%">
  <% unless session[:member] %>
    <%= render 'member/signup' %>
  <% end %>
</div>
<br>
<div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details »</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details »</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details »</a></p>
        </div>
      </div>
      <hr>

      <footer>
        <p>© Company 2013</p>
      </footer>

    </div>